fix: avoid non-deterministic map iteration
tendermint/farming pull request #255
Opened 2022-03-21 11:04 UTC by hallazzang

## Description

This PR makes the range-loops deterministic to avoid app hash collision.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Appropriate labels applied
- [x] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-03-21 13:49 UTC, dongsam requested changes
@hallazzang It looks omitted cherry-picking commit https://github.com/cosmosquad-labs/squad/pull/262/commits/f9ccba092f5e09ec21005f82aa7009377b77b3c0

2022-03-21 13:58 UTC, hallazzang commented
@dongsam Yes, I accidentally dropped that commit after resetting commits. Thanks for the catch.

2022-03-21 14:25 UTC, dongsam approved these changes

2022-03-22 05:50 UTC, kogisin approved these changes

2022-03-22 05:53 UTC, merged